name: mkdocs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          pip install pymdown-extensions
          pip install mkdocs-git-revision-date-plugin
          pip install mkdocs-bibtex
          pip install mkdocs-img2fig-plugin
          pip install mkdocs-minify-plugin
          pip install mkdocs-simple-hooks
      - run: mkdocs gh-deploy --force
